server:
  port: 80
spring:
  application:
    name: cloud-consumer-feign-service
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
feign:
  client:
    config:
      default:
        readTimeout: 5000
        connectTimeout: 5000
ribbon: #设置Feign客户端调用超时时间
  ReadTimeOut: 5000 #指的是建立连接所需要的的时间
  ConnectTimeOut: 5000 #指的是建立连接之后，服务器读取资源需要的时间
logging:
  level:
    com.atguigu.service.PaymentFeignService: debug

